### ISSUE TITLE
Why the $dart2js transformer in pubspec.yaml?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/labs#24]
``` yaml
transformers:
- $dart2js:
    $include: []
```

CC @sgjesse @mkustermann
